recipe: drupal9
config:
  webroot: web
  database: mariadb

tooling:
  build-app:
    description: "Download and build application resources"
    service: appserver
    cmd: bash /app/local/scripts/build-app.sh
  clean:
    description: "Delete downloaded and built resources"
    service: appserver
    cmd: bash /app/local/scripts/clean.sh
  install-app:
    description: "Install application"
    service: appserver
    cmd: bash /app/local/scripts/install-app.sh
  xdebug:
    description: "Loading Xdebug in a user defined mode."
    service: appserver
    user: root
    cmd: bash /app/local/scripts/xdebug.sh

services:
  appserver:
    xdebug: false
    config:
      php: configs/php/xdebug.ini
    overrides:
      environment:
        DRUSH_OPTIONS_ROOT: '/app/web'
        PHP_IDE_CONFIG: "serverName=appserver"
        XDEBUG_MODE:

  cache:
    type: redis:6
    portforward: true

  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
